/** Generated by AWAG ver.2.0.0.GIT-e0917bf.BUILD-20170421-1451+0900 */

package com.ibm.salessample.dto;

import java.util.List;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import javax.ws.rs.PathParam;
import javax.ws.rs.QueryParam;
import com.ibm.jp.awag2.common.entity.DisplayName;
import com.ibm.jp.awag2.common.validator.DateTime;
import com.ibm.jp.awag2.common.validator.Number;
import com.ibm.jp.awag2.common.validator.StringFormat;
import com.ibm.jp.awag2.common.dto.DTOBase;

/**
 * ApproveList.StaffのInput DTOクラス。
 *
 */
public class ApproveListInputDTOStaff  extends DTOBase {

	/** 担当者ID(employeeno) */
	@DisplayName(name = "担当者ID")
	private String employeeno;

	/** 担当者名(name) */
	@DisplayName(name = "担当者名")
	private String name;
	

	/**
	 * 担当者IDを取得する。
	 * @return employeeno
	 */
	public String getEmployeeno() {
		return employeeno;
	}

	/**
	 * 担当者IDを設定する。
	 * @param employeeno
	 */
	public void setEmployeeno(String employeeno) {
		this.employeeno = employeeno;
	}

	/**
	 * 担当者名を取得する。
	 * @return name
	 */
	public String getName() {
		return name;
	}

	/**
	 * 担当者名を設定する。
	 * @param name
	 */
	public void setName(String name) {
		this.name = name;
	}
	
}