/** Generated by AWAG ver.2.0.0.GIT-e0917bf.BUILD-20170421-1451+0900 */

package com.ibm.salessample.dto;

import java.util.List;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import javax.ws.rs.PathParam;
import javax.ws.rs.QueryParam;
import com.ibm.jp.awag2.common.entity.DisplayName;
import com.ibm.jp.awag2.common.validator.DateTime;
import com.ibm.jp.awag2.common.validator.Number;
import com.ibm.jp.awag2.common.validator.StringFormat;
import com.ibm.jp.awag2.common.dto.DTOBase;

/**
 * ApproveList.ApprovelogのInput DTOクラス。
 *
 */
public class ApproveListInputDTOApprovelog  extends DTOBase {

	/** お客様番号(customerid) */
	@StringFormat(type = StringFormat.Type.HALF_NUM, minLength = 8, maxLength = 8)			
	@DisplayName(name = "お客様番号")
	private String customerid;

	/** コメント(comment) */
	@StringFormat(type = StringFormat.Type.ALL, maxLength = 20)			
	@DisplayName(name = "コメント")
	private String comment;

	/** ランク(rank) */
	@StringFormat(type = StringFormat.Type.HALF_NUM_CHAR, maxLength = 3)			
	@DisplayName(name = "ランク")
	private String rank;

	/** ステータス(status) */
	@StringFormat(type = StringFormat.Type.HALF_NUM_CHAR, maxLength = 3)			
	@DisplayName(name = "ステータス")
	private String status;

	/** 承認フラグ(flag) */
	@StringFormat(type = StringFormat.Type.HALF_NUM_CHAR, maxLength = 3)			
	@DisplayName(name = "承認フラグ")
	private String flag;

	/** タイムスタンプ(version) */
	@DisplayName(name = "タイムスタンプ")
	private String version;
	

	/**
	 * お客様番号を取得する。
	 * @return customerid
	 */
	public String getCustomerid() {
		return customerid;
	}

	/**
	 * お客様番号を設定する。
	 * @param customerid
	 */
	public void setCustomerid(String customerid) {
		this.customerid = customerid;
	}

	/**
	 * コメントを取得する。
	 * @return comment
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * コメントを設定する。
	 * @param comment
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}

	/**
	 * ランクを取得する。
	 * @return rank
	 */
	public String getRank() {
		return rank;
	}

	/**
	 * ランクを設定する。
	 * @param rank
	 */
	public void setRank(String rank) {
		this.rank = rank;
	}

	/**
	 * ステータスを取得する。
	 * @return status
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * ステータスを設定する。
	 * @param status
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * 承認フラグを取得する。
	 * @return flag
	 */
	public String getFlag() {
		return flag;
	}

	/**
	 * 承認フラグを設定する。
	 * @param flag
	 */
	public void setFlag(String flag) {
		this.flag = flag;
	}

	/**
	 * タイムスタンプを取得する。
	 * @return version
	 */
	public String getVersion() {
		return version;
	}

	/**
	 * タイムスタンプを設定する。
	 * @param version
	 */
	public void setVersion(String version) {
		this.version = version;
	}
	
}