/** Generated by AWAG ver.2.0.0.GIT-e0917bf.BUILD-20170421-1451+0900 */

package com.ibm.salessample.dto;

import java.util.List;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import javax.ws.rs.PathParam;
import javax.ws.rs.QueryParam;
import com.ibm.jp.awag2.common.entity.DisplayName;
import com.ibm.jp.awag2.common.validator.DateTime;
import com.ibm.jp.awag2.common.validator.Number;
import com.ibm.jp.awag2.common.validator.StringFormat;
import com.ibm.jp.awag2.common.dto.DTOBase;

/**
 * ApproveListのInput DTOクラス。
 *
 */
public class ApproveListInputDTO  extends DTOBase {

	/** 承認一覧(list) */
	@Valid
	private List<ApproveListInputDTOList> list;
	

	/**
	 * listを取得する。
	 * @return list
	 */
	public List<ApproveListInputDTOList> getList() {
		return list;
	}

	/**
	 * listを設定する。
	 * @param list
	 */
	public void setList(List<ApproveListInputDTOList> list) {
		this.list = list;
	}
	
}