/** Generated by AWAG ver.2.0.0.GIT-e0917bf.BUILD-20170421-1451+0900 */

package com.ibm.salessample.dto;

import java.util.List;

import javax.xml.bind.annotation.XmlType;

import com.ibm.jp.awag2.common.dto.DTOBase;
import com.ibm.jp.awag2.common.util.TextUtility;

 /**
 * CTSearchCustomer.ListのOutput DTOクラス。
 *
 */
@XmlType(propOrder = {"customerid", "nameen", "name", "inchargeid", "rank", "custclass1", "checkbox"})
public class CTSearchCustomerOutputDTOList  extends DTOBase {

	/** お客様番号(customerid) */
	private String customerid;

	/** お客様名（英字）(nameen) */
	private String nameen;

	/** お客様名（全角）(name) */
	private String name;

	/** 担当ID(inchargeid) */
	private String inchargeid;

	/** お客様ランク(rank) */
	private String rank;

	/** お客様区分1(custclass1) */
	private String custclass1;

	/** 顧客承認フラグ(checkbox) */
	private String checkbox;

	/**
	 * お客様番号を取得する。
	 * @return customerid
	 */
	public String getCustomerid() {
		return customerid;
	}

	/**
	 * お客様番号を設定する。
	 * @param customerid
	 */
	public void setCustomerid(String customerid) {
		this.customerid = customerid;
	}

	/**
	 * お客様名（英字）を取得する。
	 * @return nameen
	 */
	public String getNameen() {
		return nameen;
	}

	/**
	 * お客様名（英字）を設定する。
	 * @param nameen
	 */
	public void setNameen(String nameen) {
		this.nameen = nameen;
	}

	/**
	 * お客様名（全角）を取得する。
	 * @return name
	 */
	public String getName() {
		return name;
	}

	/**
	 * お客様名（全角）を設定する。
	 * @param name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * 担当IDを取得する。
	 * @return inchargeid
	 */
	public String getInchargeid() {
		return inchargeid;
	}

	/**
	 * 担当IDを設定する。
	 * @param inchargeid
	 */
	public void setInchargeid(String inchargeid) {
		this.inchargeid = inchargeid;
	}

	/**
	 * お客様ランクを取得する。
	 * @return rank
	 */
	public String getRank() {
		return rank;
	}

	/**
	 * お客様ランクを設定する。
	 * @param rank
	 */
	public void setRank(String rank) {
		this.rank = rank;
	}

	/**
	 * お客様区分1を取得する。
	 * @return custclass1
	 */
	public String getCustclass1() {
		return custclass1;
	}

	/**
	 * お客様区分1を設定する。
	 * @param custclass1
	 */
	public void setCustclass1(String custclass1) {
		this.custclass1 = custclass1;
	}

	/**
	 * 顧客承認フラグを取得する。
	 * @return checkbox
	 */
	public String getCheckbox() {
		return checkbox;
	}

	/**
	 * 顧客承認フラグを設定する。
	 * @param checkbox
	 */
	public void setCheckbox(String checkbox) {
		this.checkbox = checkbox;
	}
}