/** Generated by AWAG ver.2.0.0.GIT-e0917bf.BUILD-20170421-1451+0900 */

package com.ibm.salessample.dto;

import java.util.List;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import javax.ws.rs.PathParam;
import javax.ws.rs.QueryParam;
import com.ibm.jp.awag2.common.entity.DisplayName;
import com.ibm.jp.awag2.common.validator.DateTime;
import com.ibm.jp.awag2.common.validator.Number;
import com.ibm.jp.awag2.common.validator.StringFormat;
import com.ibm.jp.awag2.common.dto.DTOBase;

/**
 * CTSearchCustomerのInput DTOクラス。
 *
 */
public class CTSearchCustomerInputDTO  extends DTOBase {

	/** お客様番号(customerid) */
	@QueryParam(value = "customerid")
	@DisplayName(name = "お客様番号")
	private String customerid;

	/** お客様名（英字）(nameen) */
	@QueryParam(value = "nameen")
	@DisplayName(name = "お客様名（英字）")
	private String nameen;

	/** お客様名（全角）(name) */
	@QueryParam(value = "name")
	@DisplayName(name = "お客様名（全角）")
	private String name;

	/** 担当ID(inchargeid) */
	@QueryParam(value = "inchargeid")
	@DisplayName(name = "担当ID")
	private String inchargeid;
	
	/** OR/AND検索条件(inclusiveOr) */
	@QueryParam(value = "_inclusiveor")
	private boolean inclusiveOr ;
	
	/** 最大取得件数(maxResults) */
	@QueryParam(value = "_maxResults")
	private Integer maxResults;

	/**
	 * お客様番号を取得する。
	 * @return customerid
	 */
	public String getCustomerid() {
		return customerid;
	}

	/**
	 * お客様番号を設定する。
	 * @param customerid
	 */
	public void setCustomerid(String customerid) {
		this.customerid = customerid;
	}

	/**
	 * お客様名（英字）を取得する。
	 * @return nameen
	 */
	public String getNameen() {
		return nameen;
	}

	/**
	 * お客様名（英字）を設定する。
	 * @param nameen
	 */
	public void setNameen(String nameen) {
		this.nameen = nameen;
	}

	/**
	 * お客様名（全角）を取得する。
	 * @return name
	 */
	public String getName() {
		return name;
	}

	/**
	 * お客様名（全角）を設定する。
	 * @param name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * 担当IDを取得する。
	 * @return inchargeid
	 */
	public String getInchargeid() {
		return inchargeid;
	}

	/**
	 * 担当IDを設定する。
	 * @param inchargeid
	 */
	public void setInchargeid(String inchargeid) {
		this.inchargeid = inchargeid;
	}
	
	/**
	 * OR/AND検索条件を設定する。
	 * @param inclusiveOr OR/AND検索条件
	 */
	public void setInclusiveOr(boolean inclusiveOr) {
		this.inclusiveOr = inclusiveOr;
	}
	
	/**
	 * OR/AND検索条件を取得する。
	 * @return OR/AND検索条件
	 */
	public boolean isInclusiveOr() {
		return this.inclusiveOr;
	}

	/**
	 * 最大取得件数を設定する。
	 * @param maxResults 最大取得件数
	 */
	public void setMaxResults(Integer maxResults) {
		this.maxResults = maxResults;
	}
	
	/**
	 * 最大取得件数を取得する。
	 * @return 最大取得件数
	 */
	public Integer getMaxResults() {
		return this.maxResults;
	}
}