/** Generated by AWAG ver.2.0.0.GIT-e0917bf.BUILD-20170421-1451+0900 */

package com.ibm.salessample.dto;

import java.util.List;

import javax.xml.bind.annotation.XmlType;

import com.ibm.jp.awag2.common.dto.DTOBase;
import com.ibm.jp.awag2.common.util.TextUtility;

 /**
 * GetApproveListのOutput DTOクラス。
 *
 */
@XmlType(propOrder = {"list"})
public class GetApproveListOutputDTO  extends DTOBase {

	/** 承認一覧(list) */
	private List<GetApproveListOutputDTOList> list;

	/**
	 * 承認一覧を取得する。
	 * @return list
	 */
	public List<GetApproveListOutputDTOList> getList() {
		return list;
	}

	/**
	 * 承認一覧を設定する。
	 * @param list
	 */
	public void setList(List<GetApproveListOutputDTOList> list) {
		this.list = list;
	}
}