/** Generated by AWAG ver.2.0.0.GIT-e0917bf.BUILD-20170421-1451+0900 */

package com.ibm.salessample.dto;

import java.util.List;

import javax.xml.bind.annotation.XmlType;

import com.ibm.jp.awag2.common.dto.DTOBase;
import com.ibm.jp.awag2.common.util.TextUtility;

 /**
 * GetApproveList.StaffのOutput DTOクラス。
 *
 */
@XmlType(propOrder = {"employeeno", "name"})
public class GetApproveListOutputDTOStaff  extends DTOBase {

	/** 担当者ID(employeeno) */
	private String employeeno;

	/** 担当者名(name) */
	private String name;

	/**
	 * 担当者IDを取得する。
	 * @return employeeno
	 */
	public String getEmployeeno() {
		return employeeno;
	}

	/**
	 * 担当者IDを設定する。
	 * @param employeeno
	 */
	public void setEmployeeno(String employeeno) {
		this.employeeno = employeeno;
	}

	/**
	 * 担当者名を取得する。
	 * @return name
	 */
	public String getName() {
		return name;
	}

	/**
	 * 担当者名を設定する。
	 * @param name
	 */
	public void setName(String name) {
		this.name = name;
	}
}