/** Generated by AWAG ver.2.0.0.GIT-e0917bf.BUILD-20170421-1451+0900 */

package com.ibm.salessample.dto;

import java.util.List;

import javax.xml.bind.annotation.XmlType;

import com.ibm.jp.awag2.common.dto.DTOBase;
import com.ibm.jp.awag2.common.util.TextUtility;

 /**
 * GetContactListのOutput DTOクラス。
 *
 */
@XmlType(propOrder = {"customerid", "nameen", "name", "staff", "contacts"})
public class GetContactListOutputDTO  extends DTOBase {

	/** お客様番号(customerid) */
	private String customerid;

	/** お客様名（英字）(nameen) */
	private String nameen;

	/** お客様名（全角）(name) */
	private String name;

	/** 担当者(staff) */
	private GetContactListOutputDTOStaff staff;


	/** 一覧(contacts) */
	private List<GetContactListOutputDTOContacts> contacts;

	/**
	 * お客様番号を取得する。
	 * @return customerid
	 */
	public String getCustomerid() {
		return customerid;
	}

	/**
	 * お客様番号を設定する。
	 * @param customerid
	 */
	public void setCustomerid(String customerid) {
		this.customerid = customerid;
	}

	/**
	 * お客様名（英字）を取得する。
	 * @return nameen
	 */
	public String getNameen() {
		return nameen;
	}

	/**
	 * お客様名（英字）を設定する。
	 * @param nameen
	 */
	public void setNameen(String nameen) {
		this.nameen = nameen;
	}

	/**
	 * お客様名（全角）を取得する。
	 * @return name
	 */
	public String getName() {
		return name;
	}

	/**
	 * お客様名（全角）を設定する。
	 * @param name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * 担当者を取得する。
	 * @return staff
	 */
	public GetContactListOutputDTOStaff getStaff() {
		return staff;
	}

	/**
	 * 担当者を設定する。
	 * @param staff
	 */
	public void setStaff(GetContactListOutputDTOStaff staff) {
		this.staff = staff;
	}

	/**
	 * 一覧を取得する。
	 * @return contacts
	 */
	public List<GetContactListOutputDTOContacts> getContacts() {
		return contacts;
	}

	/**
	 * 一覧を設定する。
	 * @param contacts
	 */
	public void setContacts(List<GetContactListOutputDTOContacts> contacts) {
		this.contacts = contacts;
	}
}