/** Generated by AWAG ver.2.0.0.GIT-e0917bf.BUILD-20170421-1451+0900 at 2017-05-29T11:54:42+09:00 **/
'use strict';

var contextRoot = "/api";

var MSG_SEARCH_204 = '対象のデータがありません。検索条件を見直してください。';
var MSG_GET_204 = '対象のデータを取得できませんでした。';

var app = angular.module('awag', ['ngRoute', 'awag.common',
  'awag.contact','awag.approve','awag.maintenance','awag.inputcustomer'
  ])
    /**
     * routing for home
     **/
    .config(['$routeProvider', function($routeProvider) {
        $routeProvider
            .when('/home', {
                controller: 'HomeCtrl as home',
                templateUrl: 'awag/home.html'
            })
            .otherwise({
                controller: 'HomeCtrl as home',
                redirectTo: '/home'
            });
    }]);

/**
 * controller for home page
 **/
app.controller('HomeCtrl', ['$scope', '$window', 'Context', function($scope, $window, Context) {
    $window.document.title = "AWAG2営業支援";
    this.message = Context.message;

    this.start = function() {
        delete Context.error;
        delete Context.nextModel;
        Context.vModels = {};

        if (document.getElementsByClassName('mdl-layout__drawer')[0].getAttribute('aria-hidden') == "false") {
            document.querySelector('.mdl-layout').MaterialLayout.toggleDrawer();
        }
    };

    //for material design light
    componentHandler.upgradeDom();
}]);

/**
 * work-aroud to make material design light fields work
 **/
var MKDT = function makeDirty() {

    //for material design light
    componentHandler.upgradeDom();

    var elements = document.getElementsByClassName("mdl-textfield__input");
    for (var i = 0; i < elements.length; i++) {
        if (elements[i].value == null || elements[i].value.length == 0) {
            if (elements[i].parentNode.classList.contains('is-invalid')) {
                (elements[i].parentNode.classList.remove('is-invalid'));
            }
        }
    }
}

/**
 * reset radio and checkbox without "option-AndOr"
 **/
var RSCKD = function resetChecked() {
    var elements = document.getElementsByClassName("mdl-radio__button");
    for (var i = 0; i < elements.length; i++) {
        if (elements[i].name != "option-AndOr") {
            (elements[i].parentNode.classList.remove('is-checked'));
        } else {
            if (elements[i].id == "option-And") {
                elements[i].click();
            }
        }
    }
    var elements = document.getElementsByClassName("mdl-checkbox__input");
    for (var i = 0; i < elements.length; i++) {
        (elements[i].parentNode.classList.remove('is-checked'));
    }
}

/**
 * show loading image
 **/
function showLoading() {
    document.getElementById("spinner").classList.add('is-active');
}
/**
 * hide loading image
 **/
function hideLoading() {
    document.getElementById("spinner").classList.remove('is-active');
}
