/** Generated by AWAG ver.2.0.0.GIT-e0917bf.BUILD-20170421-1451+0900 at 2017-05-29T11:54:42+09:00 **/
'use strict';
/* Services */

var common = angular.module('awag.common');

/**
 * class1Opts name/value
 **/
common.value('class1Opts', [{
  name: '',
  value: ''
}, {
  name: '個人',
  value: '100'
}, {
  name: '法人',
  value: '200'
}, {
  name: '団体',
  value: '300'
}, {
  name: '官公庁',
  value: '400'
}]);

/**
 * approveOpts name/value
 **/
common.value('approveOpts', [{
  name: '仮承認',
  value: '000'
}, {
  name: '承認',
  value: '100'
}]);

/**
 * rankOpts2 name/value
 **/
common.value('rankOpts2', [{
  name: 'Type-A',
  value: 'A00'
}, {
  name: 'Type-B',
  value: 'B00'
}]);

/**
 * rankOpts name/value
 **/
common.value('rankOpts', [{
  name: 'Aランク',
  value: 'A00'
}, {
  name: 'Bランク',
  value: 'B00'
}, {
  name: 'Cランク',
  value: 'C00'
}]);

/**
 * class2Opts name/value
 **/
common.value('class2Opts', [{
  name: '',
  value: ''
}, {
  name: 'クラス１',
  value: '100'
}, {
  name: 'クラス２',
  value: '200'
}, {
  name: 'クラス３',
  value: '300'
}, {
  name: 'クラス４',
  value: '400'
}]);

