/** Generated by AWAG ver.2.0.0.GIT-e0917bf.BUILD-20170421-1451+0900 */

package com.ibm.salessample.dao.impl;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import javax.interceptor.Interceptors;
import javax.enterprise.context.Dependent;
import javax.persistence.EntityManager;
import javax.persistence.NoResultException;
import javax.persistence.PersistenceException;
import javax.persistence.Query;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaDelete;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.JoinType;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;

import com.ibm.jp.awag2.common.dao.DAOBase;
import com.ibm.jp.awag2.common.dao.DAOParameter;
import com.ibm.jp.awag2.common.entity.JoinEntity;
import com.ibm.jp.awag2.common.logic.ServiceAppException;
import com.ibm.jp.awag2.common.logic.ServiceDBException;
import com.ibm.jp.awag2.common.dao.DAOIF;
import com.ibm.jp.awag2.common.util.MethodTraceLoggingInterceptor;
import com.ibm.salessample.entity.ADDRESS;
import com.ibm.salessample.entity.ADDRESSPK;

/**
 * 連絡先（ADDRESS）EntityのDAOクラス。
 *
 */
 @Interceptors(MethodTraceLoggingInterceptor.class)
 @Dependent
public class ADDRESSDAO extends DAOBase<ADDRESS, ADDRESSPK, Timestamp> implements DAOIF<ADDRESS, ADDRESSPK> {

	/** デフォルト最大取得件数 */
	private static int DEFAULT_MAX_RESULT = 0;

	@Override
	public Optional<ADDRESS> find(ADDRESSPK pk)  throws ServiceDBException, ServiceAppException {

		return super.findEntity(ADDRESS.class, pk);

	}

	@Override
	public Optional<ADDRESS> find(ADDRESSPK pk, List<JoinEntity> joinEntityList)  throws ServiceDBException, ServiceAppException {

		EntityManager em = super.getEntityManager();

		CriteriaBuilder cb = em.getCriteriaBuilder();
		CriteriaQuery<ADDRESS> cQuery = cb.createQuery(ADDRESS.class);

		// FROM
		Root<ADDRESS> address = cQuery.from(ADDRESS.class);

		// JOIN
		if (joinEntityList != null) {
			for (JoinEntity joinEntry :  joinEntityList) {
				recursiveJoin(address, null, joinEntry);
			}
		}

		// WHERE
		List<Predicate> preds = new ArrayList<>();

		if (pk.getCUSTOMERID() != null) {
		    preds.add(cb.equal(address.get("pk").get("CUSTOMERID"), pk.getCUSTOMERID()));
		}

		if (pk.getADDRESSCD() != null) {
		    preds.add(cb.equal(address.get("pk").get("ADDRESSCD"), pk.getADDRESSCD()));
		}
		cQuery.where(cb.and(preds.toArray(new Predicate[]{})));

	    TypedQuery<ADDRESS> tQuery = em.createQuery(cQuery);

		try {
			List<ADDRESS> addressList = tQuery.getResultList();
			if (addressList == null || addressList.isEmpty()) {
				return Optional.ofNullable(null);
			} else {
				return Optional.ofNullable(tQuery.getResultList().get(0));
			}

		} catch (PersistenceException e) {
			throw createServiceDBException(ServiceDBException.DBErrorType.OTHER, "_EDB00001", e);
		} catch (RuntimeException e) {
			throw createServiceDBException(ServiceDBException.DBErrorType.OTHER, "_EDB00001", e);
		}
	}

	@Override
	public  List<ADDRESS> findList(DAOParameter param, List<JoinEntity> joinEntityList, boolean isInclusiveOr, Integer maxResults)  throws ServiceDBException, ServiceAppException {

		EntityManager em = super.getEntityManager();

		CriteriaBuilder cb = em.getCriteriaBuilder();
		CriteriaQuery<ADDRESS> cQuery = cb.createQuery(ADDRESS.class);

		// FROM
		Root<ADDRESS> address = cQuery.from(ADDRESS.class);

		// JOIN
		if (joinEntityList != null) {
			for (JoinEntity joinEntry :  joinEntityList) {
				recursiveJoin(address, null, joinEntry);
			}
		}

		// WHERE
		List<Predicate> preds = new ArrayList<>();

		if (param.get("customerid") != null) {
		    preds.add(createPredicate(cb, address.get("pk").get("CUSTOMERID"), param.get("customerid")));
		}

		if (param.get("addresscd") != null) {
		    preds.add(createPredicate(cb, address.get("pk").get("ADDRESSCD"), param.get("addresscd")));
		}

		if (param.get("name") != null) {
		    preds.add(createPredicate(cb, address.get("NAME"), param.get("name")));
		}

		if (param.get("zip") != null) {
		    preds.add(createPredicate(cb, address.get("ZIP"), param.get("zip")));
		}

		if (param.get("address1") != null) {
		    preds.add(createPredicate(cb, address.get("ADDRESS1"), param.get("address1")));
		}

		if (param.get("address2") != null) {
		    preds.add(createPredicate(cb, address.get("ADDRESS2"), param.get("address2")));
		}

		if (param.get("address3") != null) {
		    preds.add(createPredicate(cb, address.get("ADDRESS3"), param.get("address3")));
		}

		if (param.get("tel") != null) {
		    preds.add(createPredicate(cb, address.get("TEL"), param.get("tel")));
		}

		if (param.get("version") != null) {
		    preds.add(createPredicate(cb, address.get("VERSION"), param.get("version")));
		}
		if (!preds.isEmpty()) {
			if (isInclusiveOr) {
				cQuery.where(cb.or(preds.toArray(new Predicate[]{})));
			} else {
				cQuery.where(cb.and(preds.toArray(new Predicate[]{})));
			}
		}

	    // ORDER BY
	    cQuery.orderBy(
		cb.asc(address.get("pk").get("CUSTOMERID")), 
		cb.asc(address.get("pk").get("ADDRESSCD"))
		);

	    TypedQuery<ADDRESS> tQuery = em.createQuery(cQuery);
	    if (maxResults != null && maxResults > 0) {
		    tQuery.setMaxResults(maxResults);
	    } else {
		    tQuery.setMaxResults(DEFAULT_MAX_RESULT);
	    }

		try {
			List<ADDRESS> resultList = tQuery.getResultList();
			if (resultList == null) {
				return new ArrayList<ADDRESS>();
			} else {
				return resultList;
			}
		} catch (PersistenceException e) {
			throw createServiceDBException(ServiceDBException.DBErrorType.OTHER, "_EDB00001", e);
		} catch (RuntimeException e) {
			throw createServiceDBException(ServiceDBException.DBErrorType.OTHER, "_EDB00001", e);
		}
	}

	@Override
	public void insert(ADDRESS entity) throws ServiceDBException, ServiceAppException {

		super.persistEntity(entity);

	}

	@Override
	public void insertList(List<ADDRESS> entityList) throws ServiceDBException, ServiceAppException {

		super.persistList(entityList);

	}

	@Override
	public void update(ADDRESS entity) throws ServiceDBException, ServiceAppException {

		super.mergeEntity(entity);

	}

	@Override
	public void updateList(List<ADDRESS> entityList) throws ServiceDBException, ServiceAppException {

		super.mergeList(entityList);

	}

	@Override
	public void delete(ADDRESS entity) throws ServiceDBException, ServiceAppException {

		super.removeEntity(ADDRESS.class, entity.getPk(), entity.get_resourceVersion());

	}

	@Override
	public void deleteList(List<ADDRESS> entityList) throws ServiceDBException, ServiceAppException {

		super.removeList(entityList);

	}

}
