/** Generated by AWAG ver.2.0.0.GIT-e0917bf.BUILD-20170421-1451+0900 */

package com.ibm.salessample.dao.impl;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import javax.interceptor.Interceptors;
import javax.enterprise.context.Dependent;
import javax.persistence.EntityManager;
import javax.persistence.NoResultException;
import javax.persistence.PersistenceException;
import javax.persistence.Query;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaDelete;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.JoinType;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;

import com.ibm.jp.awag2.common.dao.DAOBase;
import com.ibm.jp.awag2.common.dao.DAOParameter;
import com.ibm.jp.awag2.common.entity.JoinEntity;
import com.ibm.jp.awag2.common.logic.ServiceAppException;
import com.ibm.jp.awag2.common.logic.ServiceDBException;
import com.ibm.jp.awag2.common.dao.DAOIF;
import com.ibm.jp.awag2.common.util.MethodTraceLoggingInterceptor;
import com.ibm.salessample.entity.APPROVELOG;
import com.ibm.salessample.entity.APPROVELOGPK;

/**
 * 承認履歴（APPROVELOG）EntityのDAOクラス。
 *
 */
 @Interceptors(MethodTraceLoggingInterceptor.class)
 @Dependent
public class APPROVELOGDAO extends DAOBase<APPROVELOG, APPROVELOGPK, Timestamp> implements DAOIF<APPROVELOG, APPROVELOGPK> {

	/** デフォルト最大取得件数 */
	private static int DEFAULT_MAX_RESULT = 0;

	@Override
	public Optional<APPROVELOG> find(APPROVELOGPK pk)  throws ServiceDBException, ServiceAppException {

		return super.findEntity(APPROVELOG.class, pk);

	}

	@Override
	public Optional<APPROVELOG> find(APPROVELOGPK pk, List<JoinEntity> joinEntityList)  throws ServiceDBException, ServiceAppException {

		EntityManager em = super.getEntityManager();

		CriteriaBuilder cb = em.getCriteriaBuilder();
		CriteriaQuery<APPROVELOG> cQuery = cb.createQuery(APPROVELOG.class);

		// FROM
		Root<APPROVELOG> approvelog = cQuery.from(APPROVELOG.class);

		// JOIN
		if (joinEntityList != null) {
			for (JoinEntity joinEntry :  joinEntityList) {
				recursiveJoin(approvelog, null, joinEntry);
			}
		}

		// WHERE
		List<Predicate> preds = new ArrayList<>();

		if (pk.getCUSTOMERID() != null) {
		    preds.add(cb.equal(approvelog.get("pk").get("CUSTOMERID"), pk.getCUSTOMERID()));
		}
		cQuery.where(cb.and(preds.toArray(new Predicate[]{})));

	    TypedQuery<APPROVELOG> tQuery = em.createQuery(cQuery);

		try {
			List<APPROVELOG> approvelogList = tQuery.getResultList();
			if (approvelogList == null || approvelogList.isEmpty()) {
				return Optional.ofNullable(null);
			} else {
				return Optional.ofNullable(tQuery.getResultList().get(0));
			}

		} catch (PersistenceException e) {
			throw createServiceDBException(ServiceDBException.DBErrorType.OTHER, "_EDB00001", e);
		} catch (RuntimeException e) {
			throw createServiceDBException(ServiceDBException.DBErrorType.OTHER, "_EDB00001", e);
		}
	}

	@Override
	public  List<APPROVELOG> findList(DAOParameter param, List<JoinEntity> joinEntityList, boolean isInclusiveOr, Integer maxResults)  throws ServiceDBException, ServiceAppException {

		EntityManager em = super.getEntityManager();

		CriteriaBuilder cb = em.getCriteriaBuilder();
		CriteriaQuery<APPROVELOG> cQuery = cb.createQuery(APPROVELOG.class);

		// FROM
		Root<APPROVELOG> approvelog = cQuery.from(APPROVELOG.class);

		// JOIN
		if (joinEntityList != null) {
			for (JoinEntity joinEntry :  joinEntityList) {
				recursiveJoin(approvelog, null, joinEntry);
			}
		}

		// WHERE
		List<Predicate> preds = new ArrayList<>();

		if (param.get("customerid") != null) {
		    preds.add(createPredicate(cb, approvelog.get("pk").get("CUSTOMERID"), param.get("customerid")));
		}

		if (param.get("approver") != null) {
		    preds.add(createPredicate(cb, approvelog.get("APPROVER"), param.get("approver")));
		}

		if (param.get("comment") != null) {
		    preds.add(createPredicate(cb, approvelog.get("COMMENT"), param.get("comment")));
		}

		if (param.get("rank") != null) {
		    preds.add(createPredicate(cb, approvelog.get("RANK"), param.get("rank")));
		}

		if (param.get("status") != null) {
		    preds.add(createPredicate(cb, approvelog.get("STATUS"), param.get("status")));
		}

		if (param.get("flag") != null) {
		    preds.add(createPredicate(cb, approvelog.get("FLAG"), param.get("flag")));
		}

		if (param.get("version") != null) {
		    preds.add(createPredicate(cb, approvelog.get("VERSION"), param.get("version")));
		}
		if (!preds.isEmpty()) {
			if (isInclusiveOr) {
				cQuery.where(cb.or(preds.toArray(new Predicate[]{})));
			} else {
				cQuery.where(cb.and(preds.toArray(new Predicate[]{})));
			}
		}

	    // ORDER BY
	    cQuery.orderBy(
		cb.asc(approvelog.get("pk").get("CUSTOMERID"))
		);

	    TypedQuery<APPROVELOG> tQuery = em.createQuery(cQuery);
	    if (maxResults != null && maxResults > 0) {
		    tQuery.setMaxResults(maxResults);
	    } else {
		    tQuery.setMaxResults(DEFAULT_MAX_RESULT);
	    }

		try {
			List<APPROVELOG> resultList = tQuery.getResultList();
			if (resultList == null) {
				return new ArrayList<APPROVELOG>();
			} else {
				return resultList;
			}
		} catch (PersistenceException e) {
			throw createServiceDBException(ServiceDBException.DBErrorType.OTHER, "_EDB00001", e);
		} catch (RuntimeException e) {
			throw createServiceDBException(ServiceDBException.DBErrorType.OTHER, "_EDB00001", e);
		}
	}

	@Override
	public void insert(APPROVELOG entity) throws ServiceDBException, ServiceAppException {

		super.persistEntity(entity);

	}

	@Override
	public void insertList(List<APPROVELOG> entityList) throws ServiceDBException, ServiceAppException {

		super.persistList(entityList);

	}

	@Override
	public void update(APPROVELOG entity) throws ServiceDBException, ServiceAppException {

		super.mergeEntity(entity);

	}

	@Override
	public void updateList(List<APPROVELOG> entityList) throws ServiceDBException, ServiceAppException {

		super.mergeList(entityList);

	}

	@Override
	public void delete(APPROVELOG entity) throws ServiceDBException, ServiceAppException {

		super.removeEntity(APPROVELOG.class, entity.getPk(), entity.get_resourceVersion());

	}

	@Override
	public void deleteList(List<APPROVELOG> entityList) throws ServiceDBException, ServiceAppException {

		super.removeList(entityList);

	}

}
