/** Generated by AWAG ver.2.0.0.GIT-e0917bf.BUILD-20170421-1451+0900 */

package com.ibm.salessample.dao.impl;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import javax.interceptor.Interceptors;
import javax.enterprise.context.Dependent;
import javax.persistence.EntityManager;
import javax.persistence.NoResultException;
import javax.persistence.PersistenceException;
import javax.persistence.Query;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaDelete;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.JoinType;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;

import com.ibm.jp.awag2.common.dao.DAOBase;
import com.ibm.jp.awag2.common.dao.DAOParameter;
import com.ibm.jp.awag2.common.entity.JoinEntity;
import com.ibm.jp.awag2.common.logic.ServiceAppException;
import com.ibm.jp.awag2.common.logic.ServiceDBException;
import com.ibm.jp.awag2.common.dao.DAOIF;
import com.ibm.jp.awag2.common.util.MethodTraceLoggingInterceptor;
import com.ibm.salessample.entity.CONTACT;
import com.ibm.salessample.entity.CONTACTPK;

/**
 * コンタクト履歴（CONTACT）EntityのDAOクラス。
 *
 */
 @Interceptors(MethodTraceLoggingInterceptor.class)
 @Dependent
public class CONTACTDAO extends DAOBase<CONTACT, CONTACTPK, Timestamp> implements DAOIF<CONTACT, CONTACTPK> {

	/** デフォルト最大取得件数 */
	private static int DEFAULT_MAX_RESULT = 0;

	@Override
	public Optional<CONTACT> find(CONTACTPK pk)  throws ServiceDBException, ServiceAppException {

		return super.findEntity(CONTACT.class, pk);

	}

	@Override
	public Optional<CONTACT> find(CONTACTPK pk, List<JoinEntity> joinEntityList)  throws ServiceDBException, ServiceAppException {

		EntityManager em = super.getEntityManager();

		CriteriaBuilder cb = em.getCriteriaBuilder();
		CriteriaQuery<CONTACT> cQuery = cb.createQuery(CONTACT.class);

		// FROM
		Root<CONTACT> contact = cQuery.from(CONTACT.class);

		// JOIN
		if (joinEntityList != null) {
			for (JoinEntity joinEntry :  joinEntityList) {
				recursiveJoin(contact, null, joinEntry);
			}
		}

		// WHERE
		List<Predicate> preds = new ArrayList<>();

		if (pk.getCUSTOMERID() != null) {
		    preds.add(cb.equal(contact.get("pk").get("CUSTOMERID"), pk.getCUSTOMERID()));
		}

		if (pk.getCONTACTID() != null) {
		    preds.add(cb.equal(contact.get("pk").get("CONTACTID"), pk.getCONTACTID()));
		}
		cQuery.where(cb.and(preds.toArray(new Predicate[]{})));

	    TypedQuery<CONTACT> tQuery = em.createQuery(cQuery);

		try {
			List<CONTACT> contactList = tQuery.getResultList();
			if (contactList == null || contactList.isEmpty()) {
				return Optional.ofNullable(null);
			} else {
				return Optional.ofNullable(tQuery.getResultList().get(0));
			}

		} catch (PersistenceException e) {
			throw createServiceDBException(ServiceDBException.DBErrorType.OTHER, "_EDB00001", e);
		} catch (RuntimeException e) {
			throw createServiceDBException(ServiceDBException.DBErrorType.OTHER, "_EDB00001", e);
		}
	}

	@Override
	public  List<CONTACT> findList(DAOParameter param, List<JoinEntity> joinEntityList, boolean isInclusiveOr, Integer maxResults)  throws ServiceDBException, ServiceAppException {

		EntityManager em = super.getEntityManager();

		CriteriaBuilder cb = em.getCriteriaBuilder();
		CriteriaQuery<CONTACT> cQuery = cb.createQuery(CONTACT.class);

		// FROM
		Root<CONTACT> contact = cQuery.from(CONTACT.class);

		// JOIN
		if (joinEntityList != null) {
			for (JoinEntity joinEntry :  joinEntityList) {
				recursiveJoin(contact, null, joinEntry);
			}
		}

		// WHERE
		List<Predicate> preds = new ArrayList<>();

		if (param.get("customerid") != null) {
		    preds.add(createPredicate(cb, contact.get("pk").get("CUSTOMERID"), param.get("customerid")));
		}

		if (param.get("contactid") != null) {
		    preds.add(createPredicate(cb, contact.get("pk").get("CONTACTID"), param.get("contactid")));
		}

		if (param.get("inchargeid") != null) {
		    preds.add(createPredicate(cb, contact.get("INCHARGEID"), param.get("inchargeid")));
		}

		if (param.get("description") != null) {
		    preds.add(createPredicate(cb, contact.get("DESCRIPTION"), param.get("description")));
		}

		if (param.get("salescd") != null) {
		    preds.add(createPredicate(cb, contact.get("SALESCD"), param.get("salescd")));
		}

		if (param.get("ozz") != null) {
		    preds.add(createPredicate(cb, contact.get("OZZ"), param.get("ozz")));
		}

		if (param.get("time") != null) {
		    preds.add(createPredicate(cb, contact.get("TIME"), param.get("time")));
		}
		if (!preds.isEmpty()) {
			if (isInclusiveOr) {
				cQuery.where(cb.or(preds.toArray(new Predicate[]{})));
			} else {
				cQuery.where(cb.and(preds.toArray(new Predicate[]{})));
			}
		}

	    // ORDER BY
	    cQuery.orderBy(
		cb.asc(contact.get("pk").get("CUSTOMERID")), 
		cb.asc(contact.get("pk").get("CONTACTID"))
		);

	    TypedQuery<CONTACT> tQuery = em.createQuery(cQuery);
	    if (maxResults != null && maxResults > 0) {
		    tQuery.setMaxResults(maxResults);
	    } else {
		    tQuery.setMaxResults(DEFAULT_MAX_RESULT);
	    }

		try {
			List<CONTACT> resultList = tQuery.getResultList();
			if (resultList == null) {
				return new ArrayList<CONTACT>();
			} else {
				return resultList;
			}
		} catch (PersistenceException e) {
			throw createServiceDBException(ServiceDBException.DBErrorType.OTHER, "_EDB00001", e);
		} catch (RuntimeException e) {
			throw createServiceDBException(ServiceDBException.DBErrorType.OTHER, "_EDB00001", e);
		}
	}

	@Override
	public void insert(CONTACT entity) throws ServiceDBException, ServiceAppException {

		super.persistEntity(entity);

	}

	@Override
	public void insertList(List<CONTACT> entityList) throws ServiceDBException, ServiceAppException {

		super.persistList(entityList);

	}

	@Override
	public void update(CONTACT entity) throws ServiceDBException, ServiceAppException {

		super.mergeEntity(entity);

	}

	@Override
	public void updateList(List<CONTACT> entityList) throws ServiceDBException, ServiceAppException {

		super.mergeList(entityList);

	}

	@Override
	public void delete(CONTACT entity) throws ServiceDBException, ServiceAppException {

		super.removeEntity(CONTACT.class, entity.getPk(), entity.get_resourceVersion());

	}

	@Override
	public void deleteList(List<CONTACT> entityList) throws ServiceDBException, ServiceAppException {

		super.removeList(entityList);

	}

}
