/** Generated by AWAG ver.2.0.0.GIT-e0917bf.BUILD-20170421-1451+0900 */

package com.ibm.salessample.dao.impl;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import javax.interceptor.Interceptors;
import javax.enterprise.context.Dependent;
import javax.persistence.EntityManager;
import javax.persistence.NoResultException;
import javax.persistence.PersistenceException;
import javax.persistence.Query;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaDelete;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.JoinType;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;

import com.ibm.jp.awag2.common.dao.DAOBase;
import com.ibm.jp.awag2.common.dao.DAOParameter;
import com.ibm.jp.awag2.common.entity.JoinEntity;
import com.ibm.jp.awag2.common.logic.ServiceAppException;
import com.ibm.jp.awag2.common.logic.ServiceDBException;
import com.ibm.jp.awag2.common.dao.DAOIF;
import com.ibm.jp.awag2.common.util.MethodTraceLoggingInterceptor;
import com.ibm.salessample.entity.CUSTOMER;
import com.ibm.salessample.entity.CUSTOMERPK;
import com.ibm.salessample.entity.CONTACT;
import com.ibm.salessample.entity.APPROVELOG;
import com.ibm.salessample.entity.ADDRESS;
import com.ibm.salessample.entity.STAFF;

/**
 * お客様（CUSTOMER）EntityのDAOクラス。
 *
 */
 @Interceptors(MethodTraceLoggingInterceptor.class)
 @Dependent
public class CUSTOMERDAO extends DAOBase<CUSTOMER, CUSTOMERPK, Timestamp> implements DAOIF<CUSTOMER, CUSTOMERPK> {

	/** デフォルト最大取得件数 */
	private static int DEFAULT_MAX_RESULT = 0;

	@Override
	public Optional<CUSTOMER> find(CUSTOMERPK pk)  throws ServiceDBException, ServiceAppException {

		return super.findEntity(CUSTOMER.class, pk);

	}

	@Override
	public Optional<CUSTOMER> find(CUSTOMERPK pk, List<JoinEntity> joinEntityList)  throws ServiceDBException, ServiceAppException {

		EntityManager em = super.getEntityManager();

		CriteriaBuilder cb = em.getCriteriaBuilder();
		CriteriaQuery<CUSTOMER> cQuery = cb.createQuery(CUSTOMER.class);

		// FROM
		Root<CUSTOMER> customer = cQuery.from(CUSTOMER.class);

		// JOIN
		if (joinEntityList != null) {
			for (JoinEntity joinEntry :  joinEntityList) {
				recursiveJoin(customer, null, joinEntry);
			}
		}

		// WHERE
		List<Predicate> preds = new ArrayList<>();

		if (pk.getCUSTOMERID() != null) {
		    preds.add(cb.equal(customer.get("pk").get("CUSTOMERID"), pk.getCUSTOMERID()));
		}
		cQuery.where(cb.and(preds.toArray(new Predicate[]{})));

	    TypedQuery<CUSTOMER> tQuery = em.createQuery(cQuery);

		try {
			List<CUSTOMER> customerList = tQuery.getResultList();
			if (customerList == null || customerList.isEmpty()) {
				return Optional.ofNullable(null);
			} else {
				return Optional.ofNullable(tQuery.getResultList().get(0));
			}

		} catch (PersistenceException e) {
			throw createServiceDBException(ServiceDBException.DBErrorType.OTHER, "_EDB00001", e);
		} catch (RuntimeException e) {
			throw createServiceDBException(ServiceDBException.DBErrorType.OTHER, "_EDB00001", e);
		}
	}

	@Override
	public  List<CUSTOMER> findList(DAOParameter param, List<JoinEntity> joinEntityList, boolean isInclusiveOr, Integer maxResults)  throws ServiceDBException, ServiceAppException {

		EntityManager em = super.getEntityManager();

		CriteriaBuilder cb = em.getCriteriaBuilder();
		CriteriaQuery<CUSTOMER> cQuery = cb.createQuery(CUSTOMER.class);

		// FROM
		Root<CUSTOMER> customer = cQuery.from(CUSTOMER.class);

		// JOIN
		if (joinEntityList != null) {
			for (JoinEntity joinEntry :  joinEntityList) {
				recursiveJoin(customer, null, joinEntry);
			}
		}

		// WHERE
		List<Predicate> preds = new ArrayList<>();

		if (param.get("customerid") != null) {
		    preds.add(createPredicate(cb, customer.get("pk").get("CUSTOMERID"), param.get("customerid")));
		}

		if (param.get("nameen") != null) {
		    preds.add(createPredicate(cb, customer.get("NAMEEN"), param.get("nameen")));
		}

		if (param.get("name") != null) {
		    preds.add(createPredicate(cb, customer.get("NAME"), param.get("name")));
		}

		if (param.get("inchargeid") != null) {
		    preds.add(createPredicate(cb, customer.get("INCHARGEID"), param.get("inchargeid")));
		}

		if (param.get("registereddate") != null) {
		    preds.add(createPredicate(cb, customer.get("REGISTEREDDATE"), param.get("registereddate")));
		}

		if (param.get("hiragana") != null) {
		    preds.add(createPredicate(cb, customer.get("HIRAGANA"), param.get("hiragana")));
		}

		if (param.get("katakana") != null) {
		    preds.add(createPredicate(cb, customer.get("KATAKANA"), param.get("katakana")));
		}

		if (param.get("description") != null) {
		    preds.add(createPredicate(cb, customer.get("DESCRIPTION"), param.get("description")));
		}

		if (param.get("isin") != null) {
		    preds.add(createPredicate(cb, customer.get("ISIN"), param.get("isin")));
		}

		if (param.get("houjinno") != null) {
		    preds.add(createPredicate(cb, customer.get("HOUJINNO"), param.get("houjinno")));
		}

		if (param.get("rank") != null) {
		    preds.add(createPredicate(cb, customer.get("RANK"), param.get("rank")));
		}

		if (param.get("custclass1") != null) {
		    preds.add(createPredicate(cb, customer.get("CUSTCLASS1"), param.get("custclass1")));
		}

		if (param.get("custclass2") != null) {
		    preds.add(createPredicate(cb, customer.get("CUSTCLASS2"), param.get("custclass2")));
		}

		if (param.get("checkbox") != null) {
		    preds.add(createPredicate(cb, customer.get("CHECKBOX"), param.get("checkbox")));
		}

		if (param.get("time") != null) {
		    preds.add(createPredicate(cb, customer.get("TIME"), param.get("time")));
		}
		if (!preds.isEmpty()) {
			if (isInclusiveOr) {
				cQuery.where(cb.or(preds.toArray(new Predicate[]{})));
			} else {
				cQuery.where(cb.and(preds.toArray(new Predicate[]{})));
			}
		}

	    // ORDER BY
	    cQuery.orderBy(
		cb.asc(customer.get("pk").get("CUSTOMERID"))
		);

	    TypedQuery<CUSTOMER> tQuery = em.createQuery(cQuery);
	    if (maxResults != null && maxResults > 0) {
		    tQuery.setMaxResults(maxResults);
	    } else {
		    tQuery.setMaxResults(DEFAULT_MAX_RESULT);
	    }

		try {
			List<CUSTOMER> resultList = tQuery.getResultList();
			if (resultList == null) {
				return new ArrayList<CUSTOMER>();
			} else {
				return resultList;
			}
		} catch (PersistenceException e) {
			throw createServiceDBException(ServiceDBException.DBErrorType.OTHER, "_EDB00001", e);
		} catch (RuntimeException e) {
			throw createServiceDBException(ServiceDBException.DBErrorType.OTHER, "_EDB00001", e);
		}
	}

	@Override
	public void insert(CUSTOMER entity) throws ServiceDBException, ServiceAppException {

		super.persistEntity(entity);

	}

	@Override
	public void insertList(List<CUSTOMER> entityList) throws ServiceDBException, ServiceAppException {

		super.persistList(entityList);

	}

	@Override
	public void update(CUSTOMER entity) throws ServiceDBException, ServiceAppException {

		super.mergeEntity(entity);

	}

	@Override
	public void updateList(List<CUSTOMER> entityList) throws ServiceDBException, ServiceAppException {

		super.mergeList(entityList);

	}

	@Override
	public void delete(CUSTOMER entity) throws ServiceDBException, ServiceAppException {

		super.removeEntity(CUSTOMER.class, entity.getPk(), entity.get_resourceVersion());

	}

	@Override
	public void deleteList(List<CUSTOMER> entityList) throws ServiceDBException, ServiceAppException {

		super.removeList(entityList);

	}

}
