/** Generated by AWAG ver.2.0.0.GIT-e0917bf.BUILD-20170421-1451+0900 */

package com.ibm.salessample.logic.impl;

import java.util.Map;

import javax.ejb.Stateless;
import javax.interceptor.Interceptors;

import com.ibm.jp.awag2.common.logic.ServiceAppException;
import com.ibm.jp.awag2.common.logic.ServiceDBException;
import com.ibm.jp.awag2.common.logic.ServiceIF;
import com.ibm.jp.awag2.common.util.MethodTraceLoggingInterceptor;
import com.ibm.salessample.dto.ApproveListInputDTO;
import com.ibm.salessample.dto.ApproveListOutputDTO;

/**
* ApproveList サービスのカスタマイズクラス
*
*/ 
@Interceptors(MethodTraceLoggingInterceptor.class)
@Stateless
public class ApproveListServiceCustomize extends ApproveListService implements ServiceIF<ApproveListInputDTO, ApproveListOutputDTO> {

	/* (非 Javadoc)
	 * @see com.ibm.jp.awag2.common.logic.ServiceIF#execute(com.ibm.jp.awag2.common.dto.DTOBase)
	 */
	public ApproveListOutputDTO execute(ApproveListInputDTO input) throws ServiceDBException, ServiceAppException {
		
		// CUSTOMIZE: Serviceメソッドの前後処理や置き換えを実装します。
		
		// DAOパラメータの取得
		Map<String, Object> daoParameterMap = this.processInput(input);
		
		// DAOの実行
		Map<String, Object> resultMap = this.persist(daoParameterMap);
		
		// DAO実行結果の出力DTOマッピング
		return this.processOutput(resultMap);
		
	}
	
	/*
	 * CUSTOMIZE: Serviceメソッドをカスタマイズする場合、対象のメソッドのコメントを解除して実装します。
	 *
	@Override
	protected ApproveListOutputDTO execute(ApproveListInputDTO input) throws ServiceDBException, ServiceAppException {
		return super.execute(input);
	}

	@Override
	protected Map<String, Object> processInput(ApproveListInputDTO input) throws ServiceDBException, ServiceAppException {
		return super.processInput(input);
	}

	@Override
	protected Map<String, Object> persist(Map<String, Object> daoParameterMap) throws ServiceDBException, ServiceAppException {
		return super.persist(daoParameterMap);
	}

	@Override
	protected ApproveListOutputDTO processOutput(Map<String, Object> resultMap) throws ServiceDBException, ServiceAppException {
		return super.processOutput(resultMap);
	}
	*/
}
