/** Generated by AWAG ver.2.0.0.GIT-e0917bf.BUILD-20170421-1451+0900 */

package com.ibm.salessample.logic.impl;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

import javax.ejb.Stateless;
import javax.inject.Inject;

import com.ibm.jp.awag2.common.dao.DAOBase.SelectWhereOperator;
import com.ibm.jp.awag2.common.dao.DAOParameter;
import com.ibm.jp.awag2.common.entity.JoinEntity;
import com.ibm.jp.awag2.common.logic.ServiceAppException;
import com.ibm.jp.awag2.common.logic.ServiceBase;
import com.ibm.jp.awag2.common.logic.ServiceDBException;
import com.ibm.salessample.dto.DeleteContactInputDTO;
import com.ibm.salessample.dto.DeleteContactOutputDTO;
import com.ibm.salessample.dao.impl.CONTACTCustomizeDAO;
import com.ibm.salessample.entity.CONTACT;
import com.ibm.salessample.entity.CONTACTPK;

/**
* コンタクト履歴削除 サービスクラス（DeleteContact）
* コンタクト履歴削除
*/ 
@Stateless
public class DeleteContactService extends ServiceBase {


	/** DAOパラメーターマップのキー（CONTACT） */
	protected static final String DAO_PARAM_MAP_KEY_CONTACT = "contact";


	/** DAOパラメーターマップのキー（CONTACTのJoinList） */
	protected static final String DAO_PARAM_MAP_KEY_CONTACT_JOIN = "joinEntityListForCONTACT";

	/** CONTACTテーブルDAO */
	@Inject
	protected CONTACTCustomizeDAO contactDao;
	
	/**
	 * DBアクセス前の入力データ処理を行う。主にInputDTOからDAOParameterへの詰替処理を行う。
	 * @param DeleteContactInputDTO InputDTO
	 * @return persistメソッドへの持ち回りデータを格納したMapオブジェクト
	 * @throws ServiceDBException
	 * @throws ServiceAppException
	 */
	protected Map<String, Object> processInput(DeleteContactInputDTO deletecontactinputdto)  throws ServiceDBException, ServiceAppException {
		
		Map<String, Object> daoParameterMap = new HashMap<>();
		
		// InputDTOからDAOParameterへの詰替

		CONTACT contactTmp = new CONTACT();
		if (deletecontactinputdto != null) contactTmp.setCUSTOMERID(deletecontactinputdto.getCustomerid());
		if (deletecontactinputdto != null) contactTmp.setCONTACTID(deletecontactinputdto.getContactid());
		if (deletecontactinputdto != null) contactTmp.setINCHARGEID(deletecontactinputdto.getInchargeid());
		if (deletecontactinputdto != null) contactTmp.setDESCRIPTION(deletecontactinputdto.getDescription());
		if (deletecontactinputdto != null) contactTmp.setSALESCD(deletecontactinputdto.getSalescd());
		if (deletecontactinputdto != null) contactTmp.setOZZ(deletecontactinputdto.getOzz());
		if (deletecontactinputdto != null) contactTmp.setTIME(deletecontactinputdto.getTime());
		daoParameterMap.put(DAO_PARAM_MAP_KEY_CONTACT,  contactTmp);

		return daoParameterMap;

	}
	
	/**
	 * DBアクセス処理を行う。
	 * @param daoParameterMap processInputメソッドからの持ち回りデータを格納したMapオブジェクト
	 * @return processOutputメソッドへの持ち回りデータを格納したMapオブジェクト
	 * @throws ServiceDBException
	 * @throws ServiceAppException
	 */
	 	protected Map<String, Object> persist(Map<String, Object> daoParameterMap)  throws ServiceDBException, ServiceAppException  {

		// DAO呼び出し
		Map<String, Object> resultMap = new HashMap<>();
										
		// DAOパラメータの取得
		CONTACT contact = (CONTACT) daoParameterMap.get(DAO_PARAM_MAP_KEY_CONTACT);

		// DAO呼び出し
		contactDao.delete(contact);

		return resultMap;
	}
	
	/**
	 * DBアクセス後の出力データ処理を行う。主にDBアクセス結果からOutputDTOへの詰替処理を行う。
	 * @param resultMap persistメソッドからの持ち回りデータを格納したMapオブジェクト
	 * @return OutputDTO
	 * @throws ServiceDBException
	 * @throws ServiceAppException
	 */
	 	protected DeleteContactOutputDTO processOutput(Map<String, Object> resultMap)  throws ServiceDBException, ServiceAppException {

		return new DeleteContactOutputDTO();
		
	}
}