/** Generated by AWAG ver.2.0.0.GIT-e0917bf.BUILD-20170421-1451+0900 */

package com.ibm.salessample.logic.impl;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

import javax.ejb.Stateless;
import javax.inject.Inject;

import com.ibm.jp.awag2.common.dao.DAOBase.SelectWhereOperator;
import com.ibm.jp.awag2.common.dao.DAOParameter;
import com.ibm.jp.awag2.common.entity.JoinEntity;
import com.ibm.jp.awag2.common.logic.ServiceAppException;
import com.ibm.jp.awag2.common.logic.ServiceBase;
import com.ibm.jp.awag2.common.logic.ServiceDBException;
import com.ibm.salessample.dto.MTSearchCustomerInputDTO;
import com.ibm.salessample.dto.MTSearchCustomerOutputDTO;
import com.ibm.salessample.dto.MTSearchCustomerOutputDTOList;
import com.ibm.salessample.dao.impl.CUSTOMERCustomizeDAO;
import com.ibm.salessample.entity.CUSTOMER;
import com.ibm.salessample.entity.CUSTOMERPK;
import com.ibm.salessample.dto.MTSearchCustomerOutputDTOList;

/**
* お客様検索 サービスクラス（MTSearchCustomer）
* お客様検索
*/ 
@Stateless
public class MTSearchCustomerService extends ServiceBase {

	/** RESULTマップのキー（CUSTOMER） */
	protected static final String RESULT_MAP_KEY_CUSTOMER = "customerList";

	/** DAOパラメーターマップのキー（CUSTOMER） */
	protected static final String DAO_PARAM_MAP_KEY_CUSTOMER = "customer";


	/** DAOパラメーターマップのキー（CUSTOMERのJoinList） */
	protected static final String DAO_PARAM_MAP_KEY_CUSTOMER_JOIN = "joinEntityListForCUSTOMER";

	/** CUSTOMERテーブルDAO */
	@Inject
	protected CUSTOMERCustomizeDAO customerDao;
	
	/**
	 * DBアクセス前の入力データ処理を行う。主にInputDTOからDAOParameterへの詰替処理を行う。
	 * @param MTSearchCustomerInputDTO InputDTO
	 * @return persistメソッドへの持ち回りデータを格納したMapオブジェクト
	 * @throws ServiceDBException
	 * @throws ServiceAppException
	 */
	protected Map<String, Object> processInput(MTSearchCustomerInputDTO mtsearchcustomerinputdto)  throws ServiceDBException, ServiceAppException {
		
		Map<String, Object> daoParameterMap = new HashMap<>();

		// InputDTOからDAOParameterへの詰替
		DAOParameter daoParamForCUSTOMER = (DAOParameter) Optional.ofNullable(daoParameterMap.get(DAO_PARAM_MAP_KEY_CUSTOMER)).orElse(new DAOParameter());

		if (daoParamForCUSTOMER.get("customerid") == null  && mtsearchcustomerinputdto.getCustomerid() != null) daoParamForCUSTOMER.set("customerid", mtsearchcustomerinputdto.getCustomerid());
		if (daoParamForCUSTOMER.get("nameen") == null  && mtsearchcustomerinputdto.getNameen() != null) daoParamForCUSTOMER.set("nameen", mtsearchcustomerinputdto.getNameen());
		if (daoParamForCUSTOMER.get("name") == null  && mtsearchcustomerinputdto.getName() != null) daoParamForCUSTOMER.set("name", mtsearchcustomerinputdto.getName());
		if (daoParamForCUSTOMER.get("inchargeid") == null  && mtsearchcustomerinputdto.getInchargeid() != null) daoParamForCUSTOMER.set("inchargeid", mtsearchcustomerinputdto.getInchargeid());
		if (daoParamForCUSTOMER.get("registereddate") == null  && mtsearchcustomerinputdto.getRegistereddate() != null) daoParamForCUSTOMER.set("registereddate", mtsearchcustomerinputdto.getRegistereddate());
		if (daoParamForCUSTOMER.get("hiragana") == null  && mtsearchcustomerinputdto.getHiragana() != null) daoParamForCUSTOMER.set("hiragana", mtsearchcustomerinputdto.getHiragana());
		if (daoParamForCUSTOMER.get("katakana") == null  && mtsearchcustomerinputdto.getKatakana() != null) daoParamForCUSTOMER.set("katakana", mtsearchcustomerinputdto.getKatakana());
		if (daoParamForCUSTOMER.get("description") == null  && mtsearchcustomerinputdto.getDescription() != null) daoParamForCUSTOMER.set("description", mtsearchcustomerinputdto.getDescription());
		if (daoParamForCUSTOMER.get("rank") == null  && mtsearchcustomerinputdto.getRank() != null) daoParamForCUSTOMER.set("rank", mtsearchcustomerinputdto.getRank());
		if (daoParamForCUSTOMER.get("custclass1") == null  && mtsearchcustomerinputdto.getCustclass1() != null) daoParamForCUSTOMER.set("custclass1", mtsearchcustomerinputdto.getCustclass1());
		if (daoParamForCUSTOMER.get("checkbox") == null  && mtsearchcustomerinputdto.getCheckbox() != null) daoParamForCUSTOMER.set("checkbox", mtsearchcustomerinputdto.getCheckbox());
		daoParameterMap.put(DAO_PARAM_MAP_KEY_CUSTOMER, daoParamForCUSTOMER);

		// Join対象Entity設定

		// AND,OR検索条件
		daoParameterMap.put("_isInclusiveOr", mtsearchcustomerinputdto.isInclusiveOr());

		// 最大取得件数
		daoParameterMap.put("_maxResults", mtsearchcustomerinputdto.getMaxResults());
				
		return daoParameterMap;
	}
	
	/**
	 * DBアクセス処理を行う。
	 * @param daoParameterMap processInputメソッドからの持ち回りデータを格納したMapオブジェクト
	 * @return processOutputメソッドへの持ち回りデータを格納したMapオブジェクト
	 * @throws ServiceDBException
	 * @throws ServiceAppException
	 */
	 	protected Map<String, Object> persist(Map<String, Object> daoParameterMap)  throws ServiceDBException, ServiceAppException  {
		
		// DAOパラメータの取得
		DAOParameter daoParamForCUSTOMER = (DAOParameter) daoParameterMap.get(DAO_PARAM_MAP_KEY_CUSTOMER);

		// Join対象Entityの取得

		// DAO呼び出し
		Map<String, Object> resultMap = new HashMap<>();
		
		List<CUSTOMER> customerList = customerDao.findList(daoParamForCUSTOMER, null, (boolean) daoParameterMap.get("_isInclusiveOr"), (Integer) daoParameterMap.get("_maxResults"));
		if (!customerList.isEmpty()) {
			resultMap.put(RESULT_MAP_KEY_CUSTOMER, customerList);
		}

		return resultMap;
	}
	
	/**
	 * DBアクセス後の出力データ処理を行う。主にDBアクセス結果からOutputDTOへの詰替処理を行う。
	 * @param resultMap persistメソッドからの持ち回りデータを格納したMapオブジェクト
	 * @return OutputDTO
	 * @throws ServiceDBException
	 * @throws ServiceAppException
	 */
	 	protected MTSearchCustomerOutputDTO processOutput(Map<String, Object> resultMap)  throws ServiceDBException, ServiceAppException {

		if (resultMap.isEmpty()) {
			return null;
		}
		
		// DAO実行結果の取得
		List<CUSTOMER> customerList = (List<CUSTOMER>) resultMap.get(RESULT_MAP_KEY_CUSTOMER);

		// DAO実行結果からOutputDTOへの詰替

		MTSearchCustomerOutputDTO mtsearchcustomeroutputdtoTmp = new MTSearchCustomerOutputDTO();

		List<MTSearchCustomerOutputDTOList> mtsearchcustomeroutputdtolistTmpWrap = null;
		if (customerList != null && !customerList.isEmpty()) mtsearchcustomeroutputdtolistTmpWrap = new ArrayList<>();
		if (customerList != null && !customerList.isEmpty()) {
		for (CUSTOMER customer : customerList) {
			MTSearchCustomerOutputDTOList mtsearchcustomeroutputdtolistTmp = new MTSearchCustomerOutputDTOList();	
			if (customer != null) mtsearchcustomeroutputdtolistTmp.setCustomerid(customer.getCUSTOMERID());
			if (customer != null) mtsearchcustomeroutputdtolistTmp.setNameen(customer.getNAMEEN());
			if (customer != null) mtsearchcustomeroutputdtolistTmp.setName(customer.getNAME());
			if (customer != null) mtsearchcustomeroutputdtolistTmp.setInchargeid(customer.getINCHARGEID());
			if (customer != null) mtsearchcustomeroutputdtolistTmp.setRegistereddate(customer.getREGISTEREDDATE());
			if (customer != null) mtsearchcustomeroutputdtolistTmp.setHiragana(customer.getHIRAGANA());
			if (customer != null) mtsearchcustomeroutputdtolistTmp.setKatakana(customer.getKATAKANA());
			if (customer != null) mtsearchcustomeroutputdtolistTmp.setDescription(customer.getDESCRIPTION());
			if (customer != null) mtsearchcustomeroutputdtolistTmp.setIsin(customer.getISIN());
			if (customer != null) mtsearchcustomeroutputdtolistTmp.setHoujinno(customer.getHOUJINNO());
			if (customer != null) mtsearchcustomeroutputdtolistTmp.setRank(customer.getRANK());
			if (customer != null) mtsearchcustomeroutputdtolistTmp.setCustclass1(customer.getCUSTCLASS1());
			if (customer != null) mtsearchcustomeroutputdtolistTmp.setCustclass2(customer.getCUSTCLASS2());
			if (customer != null) mtsearchcustomeroutputdtolistTmp.setCheckbox(customer.getCHECKBOX());
			if (customer != null) mtsearchcustomeroutputdtolistTmp.setTime(customer.getTIME());
			mtsearchcustomeroutputdtolistTmpWrap.add(mtsearchcustomeroutputdtolistTmp);
		}
		}
		mtsearchcustomeroutputdtoTmp.setList(mtsearchcustomeroutputdtolistTmpWrap);
		return mtsearchcustomeroutputdtoTmp;
	}}