/** Generated by AWAG ver.2.0.0.GIT-e0917bf.BUILD-20170421-1451+0900 */

package com.ibm.salessample.resource.impl;

import javax.enterprise.context.Dependent;
import javax.inject.Inject;
import javax.interceptor.Interceptors;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.ResponseBuilder;
import javax.ws.rs.core.Response.Status;
import com.ibm.jp.awag2.common.logic.ServiceAppException;
import com.ibm.jp.awag2.common.logic.ServiceDBException;
import com.ibm.jp.awag2.common.logic.ServiceIF;
import com.ibm.jp.awag2.common.util.MethodTraceLoggingInterceptor;
import com.ibm.salessample.dto.DeleteContactInputDTO;
import com.ibm.salessample.dto.DeleteContactOutputDTO;


/**
* コンタクト履歴削除 リソースクラス（DeleteContact）
*
*/ 
 @Interceptors(MethodTraceLoggingInterceptor.class)
@Dependent
public class DeleteContactResource {

	/** コンタクト履歴削除 Service（DeleteContact） */
	@Inject
	private ServiceIF<DeleteContactInputDTO, DeleteContactOutputDTO> service;

	public Response execute(DeleteContactInputDTO input) throws ServiceDBException, ServiceAppException {
		
		// CUSTOMIZE: ビジネスロジック前処理を実装
		
		DeleteContactOutputDTO result = service.execute(input);

		// CUSTOMIZE: ビジネスロジック後処理を実装
		
		ResponseBuilder rb = Response.ok(result);
	
		return rb.build();
	}
}

