/** Generated by AWAG ver.2.0.0.GIT-e0917bf.BUILD-20170421-1451+0900 */

package com.ibm.salessample.resource;

import javax.inject.Inject;
import javax.ws.rs.BeanParam;
import javax.ws.rs.Consumes;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.ResponseBuilder;
import javax.ws.rs.core.Response.Status;

import com.ibm.jp.awag2.common.logic.ServiceAppException;
import com.ibm.jp.awag2.common.logic.ServiceDBException;
import com.ibm.jp.awag2.common.resource.ResourceManagerBase;
import com.ibm.jp.awag2.common.validator.ValidationException;
import com.ibm.salessample.dto.GetApproveListInputDTO;
import com.ibm.salessample.resource.impl.GetApproveListResource;
 
/**
* 承認対象一覧取得 リソース・マネージャクラス（GetApproveList）
* 承認対象一覧取得
*/ 
@Path("/approvelist/")
public class GetApproveListResourceManager extends ResourceManagerBase {
	
	@Inject 
	private GetApproveListResource getapprovelistResource;
	
	@GET
	@Consumes({ MediaType.APPLICATION_JSON, MediaType.TEXT_XML })
	@Produces({ MediaType.APPLICATION_JSON, MediaType.TEXT_XML })
	public Response execute(@BeanParam GetApproveListInputDTO input) throws ServiceDBException, ServiceAppException, ValidationException {
		
		// 単項目入力チェック
		super.validateBean(input);
		
		Response response = getapprovelistResource.execute(input);

		ResponseBuilder rb = null;
		if (!response.hasEntity()) {
			return response.status(Status.NO_CONTENT).build();
		} else {
			return response;
		}
	}
}
