/** Generated by AWAG ver.2.0.0.GIT-e0917bf.BUILD-20170421-1451+0900 */

package com.ibm.salessample.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import com.ibm.jp.awag2.common.entity.DisplayName;
import com.ibm.jp.awag2.common.entity.PKBase;
import static com.ibm.jp.awag2.common.util.TextUtility.*;

/**
 * 連絡先のPKクラス。
 *
 */
@Embeddable
public class ADDRESSPK extends PKBase implements Serializable{

	/** お客様番号(CUSTOMERID) */
	@DisplayName(name = "お客様番号")
	private String customerid;

	/** 連絡先ID(ADDRESSCD) */
	@DisplayName(name = "連絡先ID")
	private String addresscd;

	/**
	 * デフォルト・コンストラクタ。
	 */
	public ADDRESSPK() {}

	/**
	 * PKのフィールド値を指定してインスタンスを初期化する。
	 * @param CUSTOMERID お客様番号
	 * @param ADDRESSCD 連絡先ID
	 */
	public ADDRESSPK (String customerid, String addresscd) {
		super();

		this.setCUSTOMERID(customerid);
		this.setADDRESSCD(addresscd);
	}

	/**
	 * お客様番号を取得する。
	 * @return CUSTOMERID
	 */
	@Column(name = "customerid")
	public String getCUSTOMERID() {
		return this.customerid;
	}

	/**
	 * お客様番号を設定する。
	 * @param customerid
	 */
	public void setCUSTOMERID(String customerid) {
		this.customerid = emptyStringToNull(customerid);
	}
	/**
	 * 連絡先IDを取得する。
	 * @return ADDRESSCD
	 */
	@Column(name = "addresscd")
	public String getADDRESSCD() {
		return this.addresscd;
	}

	/**
	 * 連絡先idを設定する。
	 * @param addresscd
	 */
	public void setADDRESSCD(String addresscd) {
		this.addresscd = emptyStringToNull(addresscd);
	}

	/**
	 * このPKオブジェクトが指定したオブジェクトと一致するか確認する。
	 */
	@Override
	public boolean equals(Object other) {
		if (this == other) {
			return true;
		}
		if (!(other instanceof ADDRESSPK)) {
			return false;
		}
		ADDRESSPK castOther = (ADDRESSPK) other;
		return this.customerid.equals(castOther.customerid) && this.addresscd.equals(castOther.addresscd);
	}

	/**
	 * PKオブジェクトのハッシュコードを取得する。
	 */
	@Override
	public int hashCode() {

		final int prime = 31;
		int hash = 17;
		hash = hash * prime + ((this.customerid != null) ? this.customerid : "").hashCode();
		hash = hash * prime + ((this.addresscd != null) ? this.addresscd : "").hashCode();

		return hash;
	}

	/**
	 * PKオブジェクトの文字列表現を取得する。
	 */
	@Override
	public String toString() {
		String ret = this.customerid + "," + this.addresscd;		
		return ret;
	}

	/**
	 * PKオブジェクトの表示表文字列表現を取得する。
	 */
	@Override
	public String toDisplayString() {
		String ret = "お客様番号:" + this.customerid + "," + "連絡先ID:" + this.addresscd;		
		return ret;
	}
}