/** Generated by AWAG ver.2.0.0.GIT-e0917bf.BUILD-20170421-1451+0900 */

package com.ibm.salessample.entity;

import static com.ibm.jp.awag2.common.util.TextUtility.emptyStringToNull;

import java.sql.Timestamp;
import java.util.List;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.Version;

import com.ibm.jp.awag2.common.entity.EntityBase;
import com.ibm.jp.awag2.common.entity.ResourceVersionNotlockImpl;
import com.ibm.jp.awag2.common.entity.ResourceVersionLongImpl;
import com.ibm.jp.awag2.common.entity.ResourceVersionTimestampImpl;

/**
 * 連絡先のEntityクラス。
 *
 */
@Entity
@Access(AccessType.PROPERTY)
@Table(name = "address")
public class ADDRESS extends EntityBase <ADDRESSPK, Timestamp> {

	/** 主キー */
	private ADDRESSPK pk = new ADDRESSPK();
	
	/** 宛先名(NAME) */
	private String name;
	
	/** 郵便番号(ZIP) */
	private String zip;
	
	/** 住所１(ADDRESS1) */
	private String address1;
	
	/** 住所２(ADDRESS2) */
	private String address2;
	
	/** 住所３(ADDRESS3) */
	private String address3;
	
	/** 電話番号(TEL) */
	private String tel;
	
	/** 更新日付(VERSION) */
	private String _version;
	

	/**
	 * デフォルト・コンストラクタ。
	 */
	public ADDRESS() {
		super();
		super._resourceVersion = new ResourceVersionTimestampImpl();
	}

	/**
	 * Entityのフィールド値を指定してインスタンスを初期化する。
	 * @param customerid お客様番号
	 * @param addresscd 連絡先ID
	 * @param name 宛先名
	 * @param zip 郵便番号
	 * @param address1 住所１
	 * @param address2 住所２
	 * @param address3 住所３
	 * @param tel 電話番号
	 * @param version 更新日付
	 */
	public ADDRESS (String customerid, String addresscd, String name, String zip, String address1, String address2, String address3, String tel, String version) {
		super._resourceVersion = new ResourceVersionTimestampImpl();
		
		this.setCUSTOMERID(customerid);
		this.setADDRESSCD(addresscd);
		this.setNAME(name);
		this.setZIP(zip);
		this.setADDRESS1(address1);
		this.setADDRESS2(address2);
		this.setADDRESS3(address3);
		this.setTEL(tel);
		this.setVERSION(version);
	}

	/**
	 * 主キーを取得する。
	 * @return 主キーオブジェクト
	 */
	@EmbeddedId
	@Override
	public ADDRESSPK getPk() {
		return this.pk;
	}

	/**
	 * 主キーを設定する。
	 * @param 主キーオブジェクト
	 */
	@Override
	public void setPk(ADDRESSPK pk) {
		this.pk = (ADDRESSPK) pk;
	}

	/**
	 * CUSTOMERIDを取得する。
	 * @return CUSTOMERID
	 */
	@Transient	
	public String getCUSTOMERID() {
		return this.pk.getCUSTOMERID();
	}

	/**
	 * お客様番号を設定する。
	 * @param CUSTOMERID
	 */
	public void setCUSTOMERID(String customerid) {
		this.pk.setCUSTOMERID(emptyStringToNull(customerid));
	}

	/**
	 * ADDRESSCDを取得する。
	 * @return ADDRESSCD
	 */
	@Transient	
	public String getADDRESSCD() {
		return this.pk.getADDRESSCD();
	}

	/**
	 * 連絡先IDを設定する。
	 * @param ADDRESSCD
	 */
	public void setADDRESSCD(String addresscd) {
		this.pk.setADDRESSCD(emptyStringToNull(addresscd));
	}

	/**
	 * NAMEを取得する。
	 * @return NAME
	 */
	@Column(name = "name")
	public String getNAME() {
		return this.name;
	}

	/**
	 * 宛先名を設定する。
	 * @param NAME
	 */
	public void setNAME(String name) {
		this.name = emptyStringToNull(name);
	}

	/**
	 * ZIPを取得する。
	 * @return ZIP
	 */
	@Column(name = "zip")
	public String getZIP() {
		return this.zip;
	}

	/**
	 * 郵便番号を設定する。
	 * @param ZIP
	 */
	public void setZIP(String zip) {
		this.zip = emptyStringToNull(zip);
	}

	/**
	 * ADDRESS1を取得する。
	 * @return ADDRESS1
	 */
	@Column(name = "address1")
	public String getADDRESS1() {
		return this.address1;
	}

	/**
	 * 住所１を設定する。
	 * @param ADDRESS1
	 */
	public void setADDRESS1(String address1) {
		this.address1 = emptyStringToNull(address1);
	}

	/**
	 * ADDRESS2を取得する。
	 * @return ADDRESS2
	 */
	@Column(name = "address2")
	public String getADDRESS2() {
		return this.address2;
	}

	/**
	 * 住所２を設定する。
	 * @param ADDRESS2
	 */
	public void setADDRESS2(String address2) {
		this.address2 = emptyStringToNull(address2);
	}

	/**
	 * ADDRESS3を取得する。
	 * @return ADDRESS3
	 */
	@Column(name = "address3")
	public String getADDRESS3() {
		return this.address3;
	}

	/**
	 * 住所３を設定する。
	 * @param ADDRESS3
	 */
	public void setADDRESS3(String address3) {
		this.address3 = emptyStringToNull(address3);
	}

	/**
	 * TELを取得する。
	 * @return TEL
	 */
	@Column(name = "tel")
	public String getTEL() {
		return this.tel;
	}

	/**
	 * 電話番号を設定する。
	 * @param TEL
	 */
	public void setTEL(String tel) {
		this.tel = emptyStringToNull(tel);
	}

	/**
	 * VERSIONのDB値を取得する。
	 * @return VERSIONのDB値
	 */
	@Version
	@Column(name = "version")
	public Timestamp getVERSION_db() {	
		return super.get_resourceVersion();
	}

	/**
	 * 更新日付の文字列表記を取得する。
	 * @return VERSIONの文字列表記
	 */
	@Transient	
	public String getVERSION() {
		return super.get_resourceVersionString();
	}

	/**
	 * 更新日付のDB値を設定する。
	 * @param VERSIONのDB値
	 */
	public void setVERSION_db(Timestamp version) {
		super.set_resourceVersion(version);
	}

	/**
	 * 更新日付の文字列表記を設定する。
	 * @param VERSIONの文字列表記
	 */
	public void setVERSION(String version) {
		super.set_resourceVersionString(emptyStringToNull(version));
	}


}