/** Generated by AWAG ver.2.0.0.GIT-e0917bf.BUILD-20170421-1451+0900 */

package com.ibm.salessample.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import com.ibm.jp.awag2.common.entity.DisplayName;
import com.ibm.jp.awag2.common.entity.PKBase;
import static com.ibm.jp.awag2.common.util.TextUtility.*;

/**
 * 承認履歴のPKクラス。
 *
 */
@Embeddable
public class APPROVELOGPK extends PKBase implements Serializable{

	/** お客様番号(CUSTOMERID) */
	@DisplayName(name = "お客様番号")
	private String customerid;

	/**
	 * デフォルト・コンストラクタ。
	 */
	public APPROVELOGPK() {}

	/**
	 * PKのフィールド値を指定してインスタンスを初期化する。
	 * @param CUSTOMERID お客様番号
	 */
	public APPROVELOGPK (String customerid) {
		super();

		this.setCUSTOMERID(customerid);
	}

	/**
	 * お客様番号を取得する。
	 * @return CUSTOMERID
	 */
	@Column(name = "customerid")
	public String getCUSTOMERID() {
		return this.customerid;
	}

	/**
	 * お客様番号を設定する。
	 * @param customerid
	 */
	public void setCUSTOMERID(String customerid) {
		this.customerid = emptyStringToNull(customerid);
	}

	/**
	 * このPKオブジェクトが指定したオブジェクトと一致するか確認する。
	 */
	@Override
	public boolean equals(Object other) {
		if (this == other) {
			return true;
		}
		if (!(other instanceof APPROVELOGPK)) {
			return false;
		}
		APPROVELOGPK castOther = (APPROVELOGPK) other;
		return this.customerid.equals(castOther.customerid);
	}

	/**
	 * PKオブジェクトのハッシュコードを取得する。
	 */
	@Override
	public int hashCode() {

		final int prime = 31;
		int hash = 17;
		hash = hash * prime + ((this.customerid != null) ? this.customerid : "").hashCode();

		return hash;
	}

	/**
	 * PKオブジェクトの文字列表現を取得する。
	 */
	@Override
	public String toString() {
		String ret = this.customerid;		
		return ret;
	}

	/**
	 * PKオブジェクトの表示表文字列表現を取得する。
	 */
	@Override
	public String toDisplayString() {
		String ret = "お客様番号:" + this.customerid;		
		return ret;
	}
}