/** Generated by AWAG ver.2.0.0.GIT-e0917bf.BUILD-20170421-1451+0900 */

package com.ibm.salessample.entity;

import static com.ibm.jp.awag2.common.util.TextUtility.emptyStringToNull;

import java.sql.Timestamp;
import java.util.List;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.Version;

import com.ibm.jp.awag2.common.entity.EntityBase;
import com.ibm.jp.awag2.common.entity.ResourceVersionNotlockImpl;
import com.ibm.jp.awag2.common.entity.ResourceVersionLongImpl;
import com.ibm.jp.awag2.common.entity.ResourceVersionTimestampImpl;

/**
 * コンタクト履歴のEntityクラス。
 *
 */
@Entity
@Access(AccessType.PROPERTY)
@Table(name = "contact")
public class CONTACT extends EntityBase <CONTACTPK, Timestamp> {

	/** 主キー */
	private CONTACTPK pk = new CONTACTPK();
	
	/** 担当ID(INCHARGEID) */
	private String inchargeid;
	
	/** 内容(DESCRIPTION) */
	private String description;
	
	/** セールスコード(SALESCD) */
	private String salescd;
	
	/** オッズ(OZZ) */
	private String ozz;
	
	/** タイムスタンプ(TIME) */
	private String _time;
	

	/**
	 * デフォルト・コンストラクタ。
	 */
	public CONTACT() {
		super();
		super._resourceVersion = new ResourceVersionTimestampImpl();
	}

	/**
	 * Entityのフィールド値を指定してインスタンスを初期化する。
	 * @param customerid お客様番号
	 * @param contactid 履歴番号
	 * @param inchargeid 担当ID
	 * @param description 内容
	 * @param salescd セールスコード
	 * @param ozz オッズ
	 * @param time タイムスタンプ
	 */
	public CONTACT (String customerid, String contactid, String inchargeid, String description, String salescd, String ozz, String time) {
		super._resourceVersion = new ResourceVersionTimestampImpl();
		
		this.setCUSTOMERID(customerid);
		this.setCONTACTID(contactid);
		this.setINCHARGEID(inchargeid);
		this.setDESCRIPTION(description);
		this.setSALESCD(salescd);
		this.setOZZ(ozz);
		this.setTIME(time);
	}

	/**
	 * 主キーを取得する。
	 * @return 主キーオブジェクト
	 */
	@EmbeddedId
	@Override
	public CONTACTPK getPk() {
		return this.pk;
	}

	/**
	 * 主キーを設定する。
	 * @param 主キーオブジェクト
	 */
	@Override
	public void setPk(CONTACTPK pk) {
		this.pk = (CONTACTPK) pk;
	}

	/**
	 * CUSTOMERIDを取得する。
	 * @return CUSTOMERID
	 */
	@Transient	
	public String getCUSTOMERID() {
		return this.pk.getCUSTOMERID();
	}

	/**
	 * お客様番号を設定する。
	 * @param CUSTOMERID
	 */
	public void setCUSTOMERID(String customerid) {
		this.pk.setCUSTOMERID(emptyStringToNull(customerid));
	}

	/**
	 * CONTACTIDを取得する。
	 * @return CONTACTID
	 */
	@Transient	
	public String getCONTACTID() {
		return this.pk.getCONTACTID();
	}

	/**
	 * 履歴番号を設定する。
	 * @param CONTACTID
	 */
	public void setCONTACTID(String contactid) {
		this.pk.setCONTACTID(emptyStringToNull(contactid));
	}

	/**
	 * INCHARGEIDを取得する。
	 * @return INCHARGEID
	 */
	@Column(name = "inchargeid")
	public String getINCHARGEID() {
		return this.inchargeid;
	}

	/**
	 * 担当IDを設定する。
	 * @param INCHARGEID
	 */
	public void setINCHARGEID(String inchargeid) {
		this.inchargeid = emptyStringToNull(inchargeid);
	}

	/**
	 * DESCRIPTIONを取得する。
	 * @return DESCRIPTION
	 */
	@Column(name = "description")
	public String getDESCRIPTION() {
		return this.description;
	}

	/**
	 * 内容を設定する。
	 * @param DESCRIPTION
	 */
	public void setDESCRIPTION(String description) {
		this.description = emptyStringToNull(description);
	}

	/**
	 * SALESCDを取得する。
	 * @return SALESCD
	 */
	@Column(name = "salescd")
	public String getSALESCD() {
		return this.salescd;
	}

	/**
	 * セールスコードを設定する。
	 * @param SALESCD
	 */
	public void setSALESCD(String salescd) {
		this.salescd = emptyStringToNull(salescd);
	}

	/**
	 * OZZを取得する。
	 * @return OZZ
	 */
	@Column(name = "ozz")
	public String getOZZ() {
		return this.ozz;
	}

	/**
	 * オッズを設定する。
	 * @param OZZ
	 */
	public void setOZZ(String ozz) {
		this.ozz = emptyStringToNull(ozz);
	}

	/**
	 * TIMEのDB値を取得する。
	 * @return TIMEのDB値
	 */
	@Version
	@Column(name = "time")
	public Timestamp getTIME_db() {	
		return super.get_resourceVersion();
	}

	/**
	 * タイムスタンプの文字列表記を取得する。
	 * @return TIMEの文字列表記
	 */
	@Transient	
	public String getTIME() {
		return super.get_resourceVersionString();
	}

	/**
	 * タイムスタンプのDB値を設定する。
	 * @param TIMEのDB値
	 */
	public void setTIME_db(Timestamp time) {
		super.set_resourceVersion(time);
	}

	/**
	 * タイムスタンプの文字列表記を設定する。
	 * @param TIMEの文字列表記
	 */
	public void setTIME(String time) {
		super.set_resourceVersionString(emptyStringToNull(time));
	}


}