/** Generated by AWAG ver.2.0.0.GIT-e0917bf.BUILD-20170421-1451+0900 */

package com.ibm.salessample.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import com.ibm.jp.awag2.common.entity.DisplayName;
import com.ibm.jp.awag2.common.entity.PKBase;
import static com.ibm.jp.awag2.common.util.TextUtility.*;

/**
 * 社員のPKクラス。
 *
 */
@Embeddable
public class STAFFPK extends PKBase implements Serializable{

	/** 従業員番号(EMPLOYEENO) */
	@DisplayName(name = "従業員番号")
	private String employeeno;

	/**
	 * デフォルト・コンストラクタ。
	 */
	public STAFFPK() {}

	/**
	 * PKのフィールド値を指定してインスタンスを初期化する。
	 * @param EMPLOYEENO 従業員番号
	 */
	public STAFFPK (String employeeno) {
		super();

		this.setEMPLOYEENO(employeeno);
	}

	/**
	 * 従業員番号を取得する。
	 * @return EMPLOYEENO
	 */
	@Column(name = "employeeno")
	public String getEMPLOYEENO() {
		return this.employeeno;
	}

	/**
	 * 従業員番号を設定する。
	 * @param employeeno
	 */
	public void setEMPLOYEENO(String employeeno) {
		this.employeeno = emptyStringToNull(employeeno);
	}

	/**
	 * このPKオブジェクトが指定したオブジェクトと一致するか確認する。
	 */
	@Override
	public boolean equals(Object other) {
		if (this == other) {
			return true;
		}
		if (!(other instanceof STAFFPK)) {
			return false;
		}
		STAFFPK castOther = (STAFFPK) other;
		return this.employeeno.equals(castOther.employeeno);
	}

	/**
	 * PKオブジェクトのハッシュコードを取得する。
	 */
	@Override
	public int hashCode() {

		final int prime = 31;
		int hash = 17;
		hash = hash * prime + ((this.employeeno != null) ? this.employeeno : "").hashCode();

		return hash;
	}

	/**
	 * PKオブジェクトの文字列表現を取得する。
	 */
	@Override
	public String toString() {
		String ret = this.employeeno;		
		return ret;
	}

	/**
	 * PKオブジェクトの表示表文字列表現を取得する。
	 */
	@Override
	public String toDisplayString() {
		String ret = "従業員番号:" + this.employeeno;		
		return ret;
	}
}